repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        description: This hook trims trailing whitespace.'

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        files: \.py$
        name: pylint
        entry: pylint
        language: system
        type: [python]
        args: ['-d', 'C,R', '--rcfile=.pylintrc']
